#!/bin/bash

SRC_SPIN_DIR=/Users/stephen/Dropbox/PropV2-Shared/Projects/P2-Click-eInk-SW
DST_SPIN_DIR="/Users/stephen/Projects/Projects-ExtGit/IronSheepProductionsLLC/Projects Propeller/P2-click-eInk/P2-Click-eInk"

(set -x;cp -p "${SRC_SPIN_DIR}"/*.spin2 "${DST_SPIN_DIR}/src")
