blank_issues_enabled: false
contact_links:
  - name: P2 Forum Community Support
    url: https://forums.parallax.com/discussion/174644/new-p2-spin2-driver-for-eink-adapter-click-board#latest
    about: Discuss the P2 driver for eINK adapter Click board™ here.

